version: "3"
name: new-admin-panel

services:
  node:
    container_name: new-admin-panel-node
    restart: no
    build:
      context: .
      dockerfile: node/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src
      # React configuration files
      - ./configurations/admin-panel/ConstantConf.js:/var/www/src/src/ConstantConf.js

  nginx:
    container_name: new-admin-panel-nginx
    depends_on:
      - node
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT_WEBSITE}:3000
    volumes:
      - ../:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
